/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'computeAcl', { get: function () { return require('./compute-acl'); } });
Object.defineProperty(exports, 'computeImageList', { get: function () { return require('./compute-image-list'); } });
Object.defineProperty(exports, 'computeImageListEntry', { get: function () { return require('./compute-image-list-entry'); } });
Object.defineProperty(exports, 'computeInstance', { get: function () { return require('./compute-instance'); } });
Object.defineProperty(exports, 'computeIpAddressAssociation', { get: function () { return require('./compute-ip-address-association'); } });
Object.defineProperty(exports, 'computeIpAddressPrefixSet', { get: function () { return require('./compute-ip-address-prefix-set'); } });
Object.defineProperty(exports, 'computeIpAddressReservation', { get: function () { return require('./compute-ip-address-reservation'); } });
Object.defineProperty(exports, 'computeIpAssociation', { get: function () { return require('./compute-ip-association'); } });
Object.defineProperty(exports, 'computeIpNetwork', { get: function () { return require('./compute-ip-network'); } });
Object.defineProperty(exports, 'computeIpNetworkExchange', { get: function () { return require('./compute-ip-network-exchange'); } });
Object.defineProperty(exports, 'computeIpReservation', { get: function () { return require('./compute-ip-reservation'); } });
Object.defineProperty(exports, 'computeMachineImage', { get: function () { return require('./compute-machine-image'); } });
Object.defineProperty(exports, 'computeOrchestratedInstance', { get: function () { return require('./compute-orchestrated-instance'); } });
Object.defineProperty(exports, 'computeRoute', { get: function () { return require('./compute-route'); } });
Object.defineProperty(exports, 'computeSecRule', { get: function () { return require('./compute-sec-rule'); } });
Object.defineProperty(exports, 'computeSecurityApplication', { get: function () { return require('./compute-security-application'); } });
Object.defineProperty(exports, 'computeSecurityAssociation', { get: function () { return require('./compute-security-association'); } });
Object.defineProperty(exports, 'computeSecurityIpList', { get: function () { return require('./compute-security-ip-list'); } });
Object.defineProperty(exports, 'computeSecurityList', { get: function () { return require('./compute-security-list'); } });
Object.defineProperty(exports, 'computeSecurityProtocol', { get: function () { return require('./compute-security-protocol'); } });
Object.defineProperty(exports, 'computeSecurityRule', { get: function () { return require('./compute-security-rule'); } });
Object.defineProperty(exports, 'computeSnapshot', { get: function () { return require('./compute-snapshot'); } });
Object.defineProperty(exports, 'computeSshKey', { get: function () { return require('./compute-ssh-key'); } });
Object.defineProperty(exports, 'computeStorageAttachment', { get: function () { return require('./compute-storage-attachment'); } });
Object.defineProperty(exports, 'computeStorageVolume', { get: function () { return require('./compute-storage-volume'); } });
Object.defineProperty(exports, 'computeStorageVolumeSnapshot', { get: function () { return require('./compute-storage-volume-snapshot'); } });
Object.defineProperty(exports, 'computeVnicSet', { get: function () { return require('./compute-vnic-set'); } });
Object.defineProperty(exports, 'computeVpnEndpointV2', { get: function () { return require('./compute-vpn-endpoint-v2'); } });
Object.defineProperty(exports, 'lbaasCertificate', { get: function () { return require('./lbaas-certificate'); } });
Object.defineProperty(exports, 'lbaasListener', { get: function () { return require('./lbaas-listener'); } });
Object.defineProperty(exports, 'lbaasLoadBalancer', { get: function () { return require('./lbaas-load-balancer'); } });
Object.defineProperty(exports, 'lbaasPolicy', { get: function () { return require('./lbaas-policy'); } });
Object.defineProperty(exports, 'lbaasServerPool', { get: function () { return require('./lbaas-server-pool'); } });
Object.defineProperty(exports, 'storageContainer', { get: function () { return require('./storage-container'); } });
Object.defineProperty(exports, 'storageObject', { get: function () { return require('./storage-object'); } });
Object.defineProperty(exports, 'dataOpcComputeImageListEntry', { get: function () { return require('./data-opc-compute-image-list-entry'); } });
Object.defineProperty(exports, 'dataOpcComputeIpAddressReservation', { get: function () { return require('./data-opc-compute-ip-address-reservation'); } });
Object.defineProperty(exports, 'dataOpcComputeIpReservation', { get: function () { return require('./data-opc-compute-ip-reservation'); } });
Object.defineProperty(exports, 'dataOpcComputeMachineImage', { get: function () { return require('./data-opc-compute-machine-image'); } });
Object.defineProperty(exports, 'dataOpcComputeNetworkInterface', { get: function () { return require('./data-opc-compute-network-interface'); } });
Object.defineProperty(exports, 'dataOpcComputeSshKey', { get: function () { return require('./data-opc-compute-ssh-key'); } });
Object.defineProperty(exports, 'dataOpcComputeStorageVolumeSnapshot', { get: function () { return require('./data-opc-compute-storage-volume-snapshot'); } });
Object.defineProperty(exports, 'dataOpcComputeVnic', { get: function () { return require('./data-opc-compute-vnic'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

